import type { Metadata } from "next";
import { Mulish, Chivo } from "next/font/google";
import "./globals.css";

const chivo = Chivo({
  variable: "--font-header",
  subsets: ["latin"],
});

const mulish = Mulish({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} ${chivo.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
